# file Makefile
# brief this file is use to build apue.2e ch02 demo
# author Jianlong Chen <jianlong99@gmail.com>
# date 2013-08-23
# $Id$

all:
	$(MAKE) -f `./systype.sh`.mk WKDIR=$(dir $(CURDIR))

clean:
	$(MAKE) -f `../systype.sh`.mk clean
