CREATE DATABASE IF NOT EXISTS blpcd;
USE blpcd;

CREATE TABLE IF NOT EXISTS cd (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	title VARCHAR(70) NOT NULL,
	artist_id INTEGER NOT NULL,
	catalogue VARCHAR(30) NOT NULL,
	notes VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS artist (
	id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS track (
	cd_id INTEGER NOT NULL,
	track_id INTEGER NOT NULL,
	title VARCHAR(70),
	PRIMARY KEY(cd_id, track_id)
);

